// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVTiutRSFmkD9uvc7xLGWO7-wAQororTE',
    appId: '1:1004258250083:web:5332484ced9143af849756',
    messagingSenderId: '1004258250083',
    projectId: 'coinplay-52f02',
    authDomain: 'coinplay-52f02.firebaseapp.com',
    storageBucket: 'coinplay-52f02.firebasestorage.app',
    measurementId: 'G-GPPLPCM6FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ8hTyz9ZeHwgpXL66-gcSbP9zj63wA2w',
    appId: '1:1004258250083:android:182ce557b819c111849756',
    messagingSenderId: '1004258250083',
    projectId: 'coinplay-52f02',
    storageBucket: 'coinplay-52f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtbRco6RAJ60p58TWREcNIokSJPcsbVs',
    appId: '1:1004258250083:ios:6404c4e445dc2dab849756',
    messagingSenderId: '1004258250083',
    projectId: 'coinplay-52f02',
    storageBucket: 'coinplay-52f02.firebasestorage.app',
    iosClientId: '1004258250083-2p7m472qv6ct56tltdu0069vtrggkk1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtbRco6RAJ60p58TWREcNIokSJPcsbVs',
    appId: '1:1004258250083:ios:6404c4e445dc2dab849756',
    messagingSenderId: '1004258250083',
    projectId: 'coinplay-52f02',
    storageBucket: 'coinplay-52f02.firebasestorage.app',
    iosClientId: '1004258250083-2p7m472qv6ct56tltdu0069vtrggkk1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVTiutRSFmkD9uvc7xLGWO7-wAQororTE',
    appId: '1:1004258250083:web:62366e772f4103b3849756',
    messagingSenderId: '1004258250083',
    projectId: 'coinplay-52f02',
    authDomain: 'coinplay-52f02.firebaseapp.com',
    storageBucket: 'coinplay-52f02.firebasestorage.app',
    measurementId: 'G-14ZF8T68TZ',
  );
}
